### ISSUE TITLE
Post-"Further working made changes" TODO

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#56]
- [x] Update license statements to use CC BY.
   - [x] Figure out translation guidance and communicate it with translators: https://github.com/whatwg/sg/issues/40.
   - [x] Figure out guidance for associated resources: https://github.com/whatwg/sg/issues/48.
   - [x] Update Bikeshed template: #23.
   - [x] Update all standards to make use of the new template and change their LICENSE resource as well.
     - [x] compat
     - [x] console
     - [x] dom
     - [x] encoding
     - [x] fetch
     - [x] fullscreen
     - [x] html
     - [x] infra
     - [x] mimesniff
     - [x] notifications
     - [x] quirks
     - [x] storage
     - [x] streams
     - [x] url
     - [x] xhr
 - [x] Make @whatbot look at incoming PRs to ensure folks have signed the participation agreement.

@xfq you may wish to follow this given your interest on IRC.
